server:
  port: ${server.port}
spring:
  application:
    name: ai-lifehub
  profiles:
    active: loc
  datasource:
    driver-class-name: ${db.mysql.driver}
    url: ${db.mysql.url}
    username: ${db.mysql.username}
    password: ${db.mysql.password}
  data:
    redis:
      host: ${db.redis.host}
      port: ${db.redis.port}
#      password: 123321
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  mail:
    host: smtp.qq.com   # 邮件服务器地址
    port: 465           # SMTP 端口（QQ: 465/587, 163: 465/994）
    username: 2913278634@qq.com  # 发送邮箱
    password: lfwsvpgrodzqdhcb  # 邮箱的授权码（不是登录密码）
    protocol: smtps
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  rabbitmq:
    host: 127.0.0.1
    port: 15672
    virtual-host: lifehub
    username: guest
    password: guest
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    space.huyuhao: debug