server:
  port: ${server.port}
spring:

  application:
    name: ai-lifehub
  profiles:
    active: loc
  datasource:
    driver-class-name: ${db.mysql.driver}
    url: ${db.mysql.url}
    username: ${db.mysql.username}
    password: ${db.mysql.password}
  data:
    redis:
      host: ${db.redis.host}
      port: ${db.redis.port}
#      password: 123321
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: space.huyuhao.po # 别名扫描包
logging:
  level:
    space.huyuhao: debug